################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
C_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CC_DEPS := 
C++_DEPS := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
SECONDARY_FLASH := 
SECONDARY_LIST := 
SECONDARY_SIZE := 
ASM_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
BSP_DISCO_F429ZI/Drivers/BSP/Components/ili9341 \
BSP_DISCO_F429ZI/Drivers/BSP/Components/l3gd20 \
BSP_DISCO_F429ZI/Drivers/BSP/Components/stmpe811 \
BSP_DISCO_F429ZI/Drivers/BSP/STM32F429I-Discovery \
BSP_DISCO_F429ZI/Utilities/Fonts \
Default/BSP_DISCO_F429ZI/Drivers/BSP/Components/ili9341 \
Default/BSP_DISCO_F429ZI/Drivers/BSP/Components/l3gd20 \
Default/BSP_DISCO_F429ZI/Drivers/BSP/Components/stmpe811 \
Default/BSP_DISCO_F429ZI/Drivers/BSP/STM32F429I-Discovery \
Default/BSP_DISCO_F429ZI/Utilities/Fonts \
Default/HX711 \
Default/LCD_DISCO_F429ZI \
Default/TFT \
Default/esp8266-driver/ESP8266/ATParser \
Default/esp8266-driver/ESP8266/ATParser/BufferedSerial/Buffer \
Default/esp8266-driver/ESP8266/ATParser/BufferedSerial \
Default/esp8266-driver/ESP8266 \
Default/esp8266-driver \
Default \
Default/mbed-os/drivers \
Default/mbed-os/events \
Default/mbed-os/events/equeue \
Default/mbed-os/features/FEATURE_LWIP/lwip-interface \
Default/mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/api \
Default/mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv4 \
Default/mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv6 \
Default/mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/core \
Default/mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/netif \
Default/mbed-os/features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM \
Default/mbed-os/features/FEATURE_LWIP/lwip-interface/lwip-sys/arch \
Default/mbed-os/features/netsocket \
Default/mbed-os/hal \
Default/mbed-os/platform \
Default/mbed-os/rtos/rtx/TARGET_CORTEX_M \
Default/mbed-os/rtos/rtx/TARGET_CORTEX_M/TARGET_RTOS_M4_M7/TOOLCHAIN_GCC \
Default/mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F429ZI \
Default/mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F429ZI/device/TOOLCHAIN_GCC_ARM \
Default/mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F429ZI/device \
Default/mbed-os/targets/TARGET_STM/TARGET_STM32F4 \
Default/mbed-os/targets/TARGET_STM/TARGET_STM32F4/device \
Default/mbed-os/targets/TARGET_STM \
. \
HX711 \
LCD_DISCO_F429ZI \
TFT \
esp8266-driver/ESP8266/ATParser \
esp8266-driver/ESP8266/ATParser/BufferedSerial/Buffer \
esp8266-driver/ESP8266/ATParser/BufferedSerial \
esp8266-driver/ESP8266 \
esp8266-driver \
mbed-os/drivers \
mbed-os/events \
mbed-os/events/equeue \
mbed-os/features/FEATURE_LWIP/lwip-interface \
mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/api \
mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv4 \
mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv6 \
mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/core \
mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/netif \
mbed-os/features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM \
mbed-os/features/FEATURE_LWIP/lwip-interface/lwip-sys/arch \
mbed-os/features/netsocket \
mbed-os/hal \
mbed-os/platform \
mbed-os/rtos \
mbed-os/rtos/rtx/TARGET_CORTEX_M \
mbed-os/rtos/rtx/TARGET_CORTEX_M/TARGET_RTOS_M4_M7/TOOLCHAIN_GCC \
mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F429ZI \
mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F429ZI/device/TOOLCHAIN_GCC_ARM \
mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F429ZI/device \
mbed-os/targets/TARGET_STM/TARGET_STM32F4 \
mbed-os/targets/TARGET_STM/TARGET_STM32F4/device \
mbed-os/targets/TARGET_STM \

