################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
C_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CC_DEPS := 
C++_DEPS := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
ASM_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
BSP_DISCO_F429ZI/Drivers/BSP/Components/ili9341 \
BSP_DISCO_F429ZI/Drivers/BSP/Components/l3gd20 \
BSP_DISCO_F429ZI/Drivers/BSP/Components/stmpe811 \
BSP_DISCO_F429ZI/Drivers/BSP/STM32F429I-Discovery \
BSP_DISCO_F429ZI/Utilities/Fonts \
Debug/BSP_DISCO_F429ZI/Drivers/BSP/Components/ili9341 \
Debug/BSP_DISCO_F429ZI/Drivers/BSP/Components/l3gd20 \
Debug/BSP_DISCO_F429ZI/Drivers/BSP/Components/stmpe811 \
Debug/BSP_DISCO_F429ZI/Drivers/BSP/STM32F429I-Discovery \
Debug/BSP_DISCO_F429ZI/Utilities/Fonts \
Debug/HX711 \
Debug/LCD_DISCO_F429ZI \
Debug/TFT \
Debug/esp8266-driver/ESP8266/ATParser \
Debug/esp8266-driver/ESP8266/ATParser/BufferedSerial/Buffer \
Debug/esp8266-driver/ESP8266/ATParser/BufferedSerial \
Debug/esp8266-driver/ESP8266 \
Debug/esp8266-driver \
Debug \
Debug/mbed-os/drivers \
Debug/mbed-os/events \
Debug/mbed-os/events/equeue \
Debug/mbed-os/features/FEATURE_UVISOR/targets/TARGET_UVISOR_UNSUPPORTED \
Debug/mbed-os/features/frameworks/greentea-client/source \
Debug/mbed-os/features/frameworks/unity/source \
Debug/mbed-os/features/frameworks/utest \
Debug/mbed-os/features/frameworks/utest/source \
Debug/mbed-os/features/mbedtls/platform/src \
Debug/mbed-os/features/mbedtls/src \
Debug/mbed-os/features/netsocket \
Debug/mbed-os/hal \
Debug/mbed-os/platform \
Debug/mbed-os/rtos \
Debug/mbed-os/rtos/rtx/TARGET_CORTEX_M \
Debug/mbed-os/rtos/rtx/TARGET_CORTEX_M/TARGET_RTOS_M4_M7/TOOLCHAIN_GCC \
Debug/mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F429ZI \
Debug/mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F429ZI/device/TOOLCHAIN_GCC_ARM \
Debug/mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F429ZI/device \
Debug/mbed-os/targets/TARGET_STM/TARGET_STM32F4 \
Debug/mbed-os/targets/TARGET_STM/TARGET_STM32F4/device \
Debug/mbed-os/targets/TARGET_STM \
HX711 \
LCD_DISCO_F429ZI \
TFT \
esp8266-driver/ESP8266/ATParser \
esp8266-driver/ESP8266/ATParser/BufferedSerial/Buffer \
esp8266-driver/ESP8266/ATParser/BufferedSerial \
esp8266-driver/ESP8266 \
esp8266-driver \
. \
mbed-os/drivers \
mbed-os/events \
mbed-os/events/equeue \
mbed-os/features/FEATURE_LWIP/lwip-interface \
mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/api \
mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv4 \
mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv6 \
mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/core \
mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/netif \
mbed-os/features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM \
mbed-os/features/FEATURE_LWIP/lwip-interface/lwip-sys/arch \
mbed-os/features/netsocket \
mbed-os/hal \
mbed-os/platform \
mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F429ZI \
mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F429ZI/device/TOOLCHAIN_GCC_ARM \
mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F429ZI/device \
mbed-os/targets/TARGET_STM/TARGET_STM32F4 \
mbed-os/targets/TARGET_STM/TARGET_STM32F4/device \
mbed-os/targets/TARGET_STM \

